

const SHOP_DATA = {
  1: {
    items: [
      {
        id: 1,
        name: 'Brown Brim',
        itemUrl: 'brown-brim',
        product_type_id: 1,
        imageUrl1: [{url: 'https://i.ibb.co/ZYW3VTp/brown-brim.png', is_main: true}],
        imageUrl2: [{url: null, is_main: false}],
        imageUrl3: [{url: null, is_main: false}],
        imageUrl4: [{url: null, is_main: false}],
        imageUrl5: [{url: null, is_main: false}],
        is_visible: true,
        is_available: true,
        price: 225,
        discount_price: null,
        description: "aaaa bbb cccc ddddd eeeee ffff gggg",
      },
      
    ]
  },
  2: {
    items: [
      {
        id: 10,
        name: 'Adidas NMD',
        itemUrl: 'adidas-nmd',
        product_type_id: 5,
        imageUrl1: [{url: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png', is_main: true}],
        imageUrl2: [{url: null, is_main: false}],
        imageUrl3: [{url: null, is_main: false}],
        imageUrl4: [{url: null, is_main: false}],
        imageUrl5: [{url: null, is_main: false}],
        is_visible: true,
        is_available: true,
        price: 220,
        discount_price: 210,
        description: "aaaa bbb cccc ddddd eeeee ffff gggg",
      },
    ]
  },
  3: {
    items: [
      {
        id: 18,
        name: 'Black Jean Shearling',
        itemUrl: 'black-jean-shearling',
        product_type_id: 5,
        imageUrl1: [{url: 'https://i.ibb.co/XzcwL5s/black-shearling.png', is_main: true}],
        imageUrl2: [{url: null, is_main: false}],
        imageUrl3: [{url: null, is_main: false}],
        imageUrl4: [{url: null, is_main: false}],
        imageUrl5: [{url: null, is_main: false}],
        is_visible: true,
        is_available: true,
        price: 125,
        discount_price: 20,
        description: "aaaa bbb cccc ddddd eeeee ffff gggg",
      },
    ]
  },
  4: {
    items: [
      {
        id: 23,
        name: 'Blue Tanktop',
        itemUrl: 'blue-tanktop',
        product_type_id: 2,
        imageUrl1: [{url: 'https://i.ibb.co/7CQVJNm/blue-tank.png', is_main: true}],
        imageUrl2: [{url: null, is_main: false}],
        imageUrl3: [{url: null, is_main: false}],
        imageUrl4: [{url: null, is_main: false}],
        imageUrl5: [{url: null, is_main: false}],
        is_visible: true,
        is_available: true,
        price: 25,
        discount_price: 20,
        description: "aaaa bbb cccc ddddd eeeee ffff gggg",
      },
    ]
  },
  5: {
    items: [
      {
        id: 30,
        name: 'Camo Down Vest',
        itemUrl: 'camo-down-vest',
        product_type_id: 4,
        imageUrl1: [{url: 'https://i.ibb.co/xJS0T3Y/camo-vest.png', is_main: true},],
        imageUrl2: [{url: null, is_main: false}],
        imageUrl3: [{url: null, is_main: false}],
        imageUrl4: [{url: null, is_main: false}],
        imageUrl5: [{url: null, is_main: false}],
        is_visible: true,
        is_available: true,
        price: 325,
        discount_price: 20,
        description: "aaaa bbb cccc ddddd eeeee ffff gggg",
      },
    ]
  }
};

export default SHOP_DATA;

// const SHOP_DATA = {
//   1: {
//     items: [
//       {
//         id: 1,
//         name: 'Brown Brim',
//         itemUrl: 'brown-brim',
//         product_type_id: 1,
//         imageUrl1: {url: 'https://i.ibb.co/ZYW3VTp/brown-brim.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 225,
//         discount_price: null,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 2,
//         name: 'Blue Beanie',
//         itemUrl: 'blue-beanie',
//         product_type_id: 4,
//         imageUrl1: {url: 'https://i.ibb.co/ypkgK0X/blue-beanie.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 180,
//         discount_price: 120,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 3,
//         name: 'Brown Cowboy',
//         itemUrl: 'brown-cowboy',
//         product_type_id: 7,
//         imageUrl1: {url: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 135,
//         discount_price: 115,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 4,
//         name: 'Grey Brim',
//         itemUrl: 'grey-brim',
//         product_type_id: 5,
//         imageUrl1: {url: 'https://i.ibb.co/RjBLWxB/grey-brim.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 205,
//         discount_price: 201,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 5,
//         name: 'Green Beanie',
//         itemUrl: 'green-beanie',
//         product_type_id: 6,
//         imageUrl1: {url: 'https://i.ibb.co/YTjW3vF/green-beanie.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_available: true,
//         price: 1800,
//         discount_price: 1500,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 6,
//         name: 'Palm Tree Cap',
//         itemUrl: 'palm-tree-cap',
//         product_type_id: 1,
//         imageUrl1: {url: 'https://i.ibb.co/rKBDvJX/palm-tree.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 140,
//         discount_price: 111,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 7,
//         name: 'Red Beanie',
//         itemUrl: 'red-beanie',
//         product_type_id: 1,
//         imageUrl1: {url: 'https://i.ibb.co/bLB646Z/red-beanie.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 430,
//         discount_price: 220,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 8,
//         name: 'Wolf Cap',
//         itemUrl: 'wolf-cap',
//         product_type_id: 8,
//         imageUrl1: {url: 'https://i.ibb.co/1f2nWMM/wolf-cap.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 142,
//         discount_price: 122,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 9,
//         name: 'Blue Snapback',
//         itemUrl: 'blue-snapback',
//         product_type_id: 6,
//         imageUrl1: {url: 'https://i.ibb.co/X2VJP2W/blue-snapback.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 111,
//         discount_price: 90,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       }
//     ]
//   },
//   2: {
//     items: [
//       {
//         id: 10,
//         name: 'Adidas NMD',
//         itemUrl: 'adidas-nmd',
//         product_type_id: 5,
//         imageUrl1: {url: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 220,
//         discount_price: 210,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 11,
//         name: 'Adidas Yeezy',
//         itemUrl: 'adidas-yeezy',
//         product_type_id: 4,
//         imageUrl1: {url: 'https://i.ibb.co/dJbG1cT/yeezy.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 280,
//         discount_price: 240,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 12,
//         name: 'Black Converse',
//         itemUrl: 'black-converse',
//         product_type_id: 4,
//         imageUrl1: {url: 'https://i.ibb.co/bPmVXyP/black-converse.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 110,
//         discount_price: 100,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 13,
//         name: 'Nike White AirForce',
//         itemUrl: 'nike-white-airforce',
//         product_type_id: 8,
//         imageUrl1: {url: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 160,
//         discount_price: 150,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 14,
//         name: 'Nike Red High Tops',
//         itemUrl: 'nike-red-high-tops',
//         product_type_id: 5,
//         imageUrl1: {url: 'https://i.ibb.co/QcvzydB/nikes-red.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 160,
//         discount_price: 120,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 15,
//         name: 'Nike Brown High Tops',
//         itemUrl: 'nike-brown-high-tops',
//         product_type_id: 9,
//         imageUrl1: {url: 'https://i.ibb.co/fMTV342/nike-brown.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 160,
//         discount_price: 120,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 16,
//         name: 'Air Jordan Limited',
//         itemUrl: 'air-jordan-limited',
//         product_type_id: 8,
//         imageUrl1: {url: 'https://i.ibb.co/w4k6Ws9/nike-bfunkyrim.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 190,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 17,
//         name: 'Timberlands',
//         itemUrl: 'timberlands',
//         product_type_id: 1,
//         imageUrl1: {url: 'https://i.ibb.co/Mhh6wBg/timberlands.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 200,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       }
//     ]
//   },
//   3: {
//     items: [
//       {
//         id: 18,
//         name: 'Black Jean Shearling',
//         itemUrl: 'black-jean-shearling',
//         product_type_id: 5,
//         imageUrl1: {url: 'https://i.ibb.co/XzcwL5s/black-shearling.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 125,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 19,
//         name: 'Blue Jean Jacket',
//         itemUrl: 'blue-jean-jacket',
//         product_type_id: 7,
//         imageUrl1: {url: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 90,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 20,
//         name: 'Grey Jean Jacket',
//         itemUrl: 'grey-jean-jacket',
//         product_type_id: 8,
//         imageUrl1: {url: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 90,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 21,
//         name: 'Brown Shearling',
//         itemUrl: 'brown-shearling',
//         product_type_id: 1,
//         imageUrl1: {url: 'https://i.ibb.co/s96FpdP/brown-shearling.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 165,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 22,
//         name: 'Tan Trench',
//         itemUrl: 'tan-trench',
//         product_type_id: 2,
//         imageUrl1: {url: 'https://i.ibb.co/M6hHc3F/brown-trench.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 185,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       }
//     ]
//   },
//   4: {
//     items: [
//       {
//         id: 23,
//         name: 'Blue Tanktop',
//         itemUrl: 'blue-tanktop',
//         product_type_id: 2,
//         imageUrl1: {url: 'https://i.ibb.co/7CQVJNm/blue-tank.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 25,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 24,
//         name: 'Floral Blouse',
//         itemUrl: 'floral-blouse',
//         product_type_id: 1,
//         imageUrl1: {url: 'https://i.ibb.co/4W2DGKm/floral-blouse.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 20,
//         discount_price: 218,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 25,
//         name: 'Floral Dress',
//         itemUrl: 'floral-dress',
//         product_type_id: 4,
//         imageUrl1: {url: 'https://i.ibb.co/ZKV18YsrYW3VTp/floral-skirt.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 80,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 26,
//         name: 'Red Dots Dress',
//         itemUrl: 'red-dots-dress',
//         product_type_id: 2,
//         imageUrl1: {url: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 80,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 27,
//         name: 'Striped Sweater',
//         itemUrl: 'striped-sweater',
//         product_type_id: 5,
//         imageUrl1: {url: 'https://i.ibb.co/KmSkMbH/striped-sweater.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 45,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 28,
//         name: 'Yellow Track Suit',
//         itemUrl: 'yellow-track-suit',
//         product_type_id: 6,
//         imageUrl1: {url: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 135,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 29,
//         name: 'White Blouse',
//         itemUrl: 'white-blouse',
//         product_type_id: 3,
//         imageUrl1: {url: 'https://i.ibb.co/qBcrsJg/white-vest.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 20,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       }
//     ]
//   },
//   5: {
//     items: [
//       {
//         id: 30,
//         name: 'Camo Down Vest',
//         itemUrl: 'camo-down-vest',
//         product_type_id: 4,
//         imageUrl1: {url: 'https://i.ibb.co/xJS0T3Y/camo-vest.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 325,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 31,
//         name: 'Floral T-shirt',
//         itemUrl: 'floral-t-shirt',
//         product_type_id: 1,
//         imageUrl1: {url: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 210,
//         discount_price: 200,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 32,
//         name: 'Black & White Longsleeve',
//         itemUrl: 'black-&-white-longsleeve',
//         product_type_id: 5,
//         imageUrl1: {url: 'https://i.ibb.co/55z32tw/long-sleeve.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 25,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 33,
//         name: 'Pink T-shirt',
//         itemUrl: 'pink-t-shirt',
//         product_type_id: 6,
//         imageUrl1: {url: 'https://i.ibb.co/RvwnBL8/pink-shirt.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 25,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 34,
//         name: 'Jean Long Sleeve',
//         itemUrl: 'jean-long-sleeve',
//         product_type_id: 9,
//         imageUrl1: {url: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 40,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       },
//       {
//         id: 35,
//         name: 'Burgundy T-shirt',
//         itemUrl: 'burgundy-t-shirt',
//         product_type_id: 3,
//         imageUrl1: {url: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png', is_main: true},
//         imageUrl2: {url: undefined, is_main: false},
//         imageUrl3: {url: undefined, is_main: false},
//         imageUrl4: {url: undefined, is_main: false},
//         imageUrl5: {url: undefined, is_main: false},
//         is_visible: true,
//         is_available: true,
//         price: 25,
//         discount_price: 20,
//         description: "aaaa bbb cccc ddddd eeeee ffff gggg",
//       }
//     ]
//   }
// };

// export default SHOP_DATA;
