const AdminActionTypes = {
    FETCH_ADMIN_STATE_START: "FETCH_ADMIN_STATE_START",
    FETCH_ADMIN_STATE_SUCCESS: "FETCH_ADMIN_STATE_SUCCESS",
    FETCH_ADMIN_STATE_FAILURE: "FETCH_ADMIN_STATE_FAILURE",
    POST_CATEGORY_TO_FIRESTORE_START: "POST_CATEGORY_TO_FIRESTORE_START",
    POST_CATEGORY_TO_FIRESTORE_SUCCESS: "POST_CATEGORY_TO_FIRESTORE_SUCCESS",
    POST_CATEGORY_TO_FIRESTORE_FAILURE: "POST_CATEGORY_TO_FIRESTORE_FAILURE",
    POST_PRODUCT_TYPE_TO_FIRESTORE_START: "POST_PRODUCT_TYPE_TO_FIRESTORE_START",
    POST_PRODUCT_TYPE_TO_FIRESTORE_SUCCESS: "POST_PRODUCT_TYPE_TO_FIRESTORE_SUCCESS",
    POST_PRODUCT_TYPE_TO_FIRESTORE_FAILURE: "POST_PRODUCT_TYPE_TO_FIRESTORE_FAILURE",
    POST_ITEM_TO_FIRESTORE_START: "POST_ITEM_TO_FIRESTORE_START",
    POST_ITEM_TO_FIRESTORE_SUCCESS: "POST_ITEM_TO_FIRESTORE_SUCCESS",
    POST_ITEM_TO_FIRESTORE_FAILURE: "POST_ITEM_TO_FIRESTORE_FAILURE",
    POST_ACCOUNT_TO_FIRESTORE_START: "POST_ACCOUNT_TO_FIRESTORE_START",
    POST_ACCOUNT_TO_FIRESTORE_SUCCESS: "POST_ACCOUNT_TO_FIRESTORE_SUCCESS",
    POST_ACCOUNT_TO_FIRESTORE_FAILURE: "POST_ACCOUNT_TO_FIRESTORE_FAILURE",
    POST_DATA_TO_FIRESTORE_START: "POST_DATA_TO_FIRESTORE_START",
    POST_DATA_TO_FIRESTORE_SUCCESS: "POST_DATA_TO_FIRESTORE_SUCCESS",
    POST_DATA_TO_FIRESTORE_FAILURE: "POST_DATA_TO_FIRESTORE_FAILURE"
}
export default AdminActionTypes;