export const FirebaseActionTypes = {
    FETCH_FIREBASE_NETWORK_STATUS_START: 'FETCH_FIREBASE_NETWORK_STATUS_START',
    FETCH_FIREBASE_NETWORK_STATUS_SUCCESS: 'FETCH_FIREBASE_NETWORK_STATUS_SUCCESS',
    FETCH_FIREBASE_NETWORK_STATUS_FAILURE: 'FETCH_FIREBASE_NETWORK_STATUS_FAILURE',
}